spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: ${DB_DRIVER} #org.postgresql.Driver
    username: ${DB_USER} #postgres
    password: ${DB_PASS} #postgres
    url: ${DB_URL} #jdbc:postgresql://localhost:5432/todoapp?useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
  jackson:
    time-zone: America/Bogota
    locale: es_CO
  sql:
    init:
      platform: postgres
server:
  port: 1200

